export enum Environment {
    DEVELOPMENT = "development",
    Development = "development",
    development = "development",
    DEV = "development",
    Dev = "development",
    dev = "development",
    STAGING = "staging",
    Staging = "staging",
    staging = "staging",
    STG = "staging",
    Stg = "staging",
    stg = "staging",
    PRODUCTION = "production",
    Production = "production",
    production = "production",
    PRD = "production",
    Prd = "production",
    prd = "production"
}
